version: 0.2
phases:
    build:
      commands:
      - echo running tests
      - ./mvnw clean install -Pbeanstalk
      - echo building the .jar file
      - ./mvnw clean package spring-boot:repackage -DskipTests -Pbeanstalk
artifacts:
    files:
    - target/zg-demo-backend-app-eb.jar
    discard-paths: yes
