branch-defaults:
  main:
    environment: Zgdemobackendapp-env-1
environment-defaults:
  Zgdemobackendapp-env:
    branch: main
    repository: zg-demo-backend-app
global:
  application_name: zg-demo-backend-app
  default_ec2_keyname: null
  default_platform: Corretto 11 running on 64bit Amazon Linux 2
  default_region: eu-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: vl
  sc: git
  workspace_type: Application
deploy:
  artifact: target/zg-demo-backend-app-eb.jar
