server:
  forward-headers-strategy: framework
  max-http-header-size: 20KB # to prevent HTTP 400 caused by huge headers; limited by CloudFront: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html

spring:
  application.name: zg-demo-backend-app
  main:
    banner-mode: 'off'

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
