spring:
  datasource:
    url: jdbc:mysql://aa115vpfld286oy.cnqkq8teqp2b.eu-central-1.rds.amazonaws.com:3306/zgora?createDatabaseIfNotExist=true

# 1. Endpoint: aa1edxcuq52rzrt.cnqkq8teqp2b.eu-central-1.rds.amazonaws.com:3306
# 2. Endpoint: aa115vpfld286oy.cnqkq8teqp2b.eu-central-1.rds.amazonaws.com:3306
