server:
  forward-headers-strategy: framework
  max-http-header-size: 20KB # to prevent HTTP 400 caused by huge headers; limited by CloudFront: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/cloudfront-limits.html

spring:
  application.name: zg-demo-backend-app
  main:
    banner-mode: 'off'
  jpa:
      open-in-view: false
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: true
          format_sql: true
      hibernate:
        ddl-auto: update
        naming:
          physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  datasource:
    url: jdbc:postgresql://localhost:5432/zgora

management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health
cloud:
  aws:
    region:
      static: eu-central-1
vl:
  datasource:
    secret: vl/zg/demo/backend/datasource
  cors:
      allowed-origins: >
        http://localhost:3000
        https://master.d3rf82j3x7kyh1.amplifyapp.com
        https://zgora.cloud.valuelogic.one
